name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      TAG: ${{ github.sha }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set lowercase owner
        id: vars
        run: |
          echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ env.owner_lc }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ env.owner_lc }}/todo-api:${{ env.TAG }} -f todo-api/Dockerfile todo-api

      - name: Push Docker image
        run: docker push ghcr.io/${{ env.owner_lc }}/todo-api:${{ env.TAG }}

      - name: Clone manifests repo (same repo in this case)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git clone https://x-access-token:${{ secrets.CICD_REPO_TOKEN }}@github.com/CSpiegelhalter/CICDpipeline.git
          cd CICDpipeline/k8s-manifest

          # Update image tag in deployment.yaml
          sed -i "s|image: .*|image: $IMAGE_NAME:$TAG|" deployment.yaml

          git add deployment.yaml
          git commit -m "Update image to $TAG"
          git push
