apiVersion: v1
kind: Service
metadata:
  name: todo-api
  labels:
    app: todo-api
spec:
  selector:
    app: todo-api
  ports:
    - name: http   # <– MUST match the `port:` in the ServiceMonitor
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
